name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
    environment:
            name: qa

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/ec2simple.json
          
      # BUILD templates
      - name: BUILD PACKER Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: build          
          target: packer/ec2simple.json
