name: Test JMeter Action

on:
  push:
    branches:
      - develop

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Action
        uses: ./
        with:
          testFilePath: tests/Condor-Sura-API.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/
