name: Test JMeter Action

on:
  push:
    branches:
      - develop

env:
  UserApi: ${{secrets.UserAPI}}
  PasswordApi: ${{secrets.PasswordAPI}}

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.3.1
        with:
          testFilePath: tests/Condor-Sura-API.jmx
          outputReportsFolder: reports/

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/
